## Preliminaries

In [1]:
import convokit

In [2]:
ROOT_DIR = '/kitchen/convokit_corpora/tennis-corpus/'

In [3]:
corpus = convokit.Corpus(ROOT_DIR)
corpus.load_info('utterance',['arcs_censored', 'question_motifs', 'question_motifs__sink'])

In [4]:
VERBOSITY = 10000

## Using PromptTypes to get types of questions

In [5]:
def question_filter(utt, aux_input={}):
    return utt.meta['is_question']
def response_filter(utt, aux_input={}):
    return (not utt.meta['is_question']) and (utt.reply_to is not None)

In [6]:
from convokit.prompt_types import PromptTypes

In [7]:
pt = PromptTypes(prompt_field='question_motifs', ref_field='arcs_censored', 
                 prompt_filter=question_filter, ref_filter=response_filter,
                 prompt_transform_field='question_motifs__sink',
                 output_field='prompt_types', prompt__tfidf_min_df=50,
                 ref__tfidf_min_df=50, 
    random_state=1000, verbosity=1)

In [8]:
pt.fit(corpus)

fitting 64571 input pairs
fitting ref tfidf model
fitting prompt tfidf model
fitting svd model
fitting 8 prompt types

In [9]:
test_utt_id = '5188_0.q'
utt = corpus.get_utterance(test_utt_id)

In [10]:
utt.text

'How do you feel? Watching the Australian Open it was very scary watching your ankle buckle. How does your ankle feel now?'

In [11]:
utt.get_info('question_motifs__sink')

['feel_*__feel_do__how>*',
 'feel_*__feel_does__feel_how feel_*__feel_now__how>*']

### Per-utterance behavior

In [12]:
utt = pt.transform_utterance(utt)

In [13]:
utt.get_info('prompt_types__prompt_repr')

[0.04614480560093584,
 0.12523176450740134,
 -0.054075221364537254,
 -0.16488221294276534,
 -0.2622154385109799,
 0.06781246550773161,
 0.3161285586302379,
 -0.11348710370703316,
 -0.30383347022247026,
 -0.36553848329504285,
 0.3362904355819349,
 0.048598494761011045,
 -0.2667895757175696,
 -0.14162106717317796,
 0.45694706042159894,
 -0.09758869692105782,
 0.06397073233732087,
 -0.04206323851119204,
 0.07013280562733451,
 0.007080600454132783,
 0.1910828848593811,
 -0.15056265464413737,
 0.21175490736928645,
 0.010463721267544844]

In [18]:
utt.get_info('prompt_types__prompt_dists.8')

[1.1542767147522681,
 1.1836322878230092,
 1.1403839094093262,
 1.080862067095506,
 1.3137305097357392,
 0.36497031797843443,
 1.3267111408021754,
 1.1126782406483375]

In [19]:
utt.get_info('prompt_types__prompt_type.8')

5.0

In [20]:
utt.get_info('prompt_types__prompt_type_dist.8')

0.36497031797843443

### model output

In [49]:
for i in range(8):
    print(i)
    pt.display_type(i, corpus=corpus, k=5)
    print('\n\n')

0
top prompt:

,0,1,2,3,4,5,6,7,type_id
try_*,0.664072,1.090674,1.319580,1.249188,1.087935,1.363645,1.155572,1.191221,0.0
how>*__keep_*__keep_how,0.669997,1.136478,1.267361,1.099178,1.043041,1.360519,1.171606,1.098759,0.0
do_*__do_do__do_what,0.686736,0.887752,1.325944,1.289076,1.022363,1.353739,1.343151,1.068488,0.0
do_*__do_do,0.690401,0.978398,1.269106,1.202296,0.977706,1.297059,1.308501,1.003302,0.0
prepare_*__prepare_for,0.692725,0.925045,1.307146,1.273835,1.118497,1.314042,1.307853,1.204177,0.0

top response:

,0,1,2,3,4,5,6,7,type_id
work_for,0.690725,1.043187,1.391620,1.146133,1.049347,1.270692,1.245960,1.159645,0.0
work_*,0.693785,1.098218,1.385079,1.114691,1.074291,1.277762,1.233976,1.176795,0.0
control_*,0.697097,1.072021,1.325468,1.252930,1.098485,1.391434,1.204093,1.116907,0.0
focus_on,0.709495,0.960281,1.259950,1.186321,1.000408,1.268750,1.241740,1.216111,0.0
focus_*,0.710258,0.970667,1.266089,1.192621,1.004985,1.265143,1.228822,1.213640,0.0

top prompts:
2020_8.q On a physical level, you're stronger maybe than ever. How do you work hard if the tournament is so close? What do you do in the gym? How do you keep the regimen going on?
['how>*__how>do work_*', 'do_*__do_in__do_what__what>* do_*__do_what__what>*__what>do', 'how>*__how>do how>*__keep_*__keep_how keep_*__keep_do']

887_3.q When you're in command of a match like that, do you actually try different things or work on something?
['try_*__try_do when>* work_*']

4182_6.q In the beginning of this season you lost in Melbourne, the final. Did you try to make a difference in preparation before today's game and why it didn't work?
['did>* try_* work_*']

3180_28.q How do you do that? What do you do?
['do_*__do_do do_*__do_how how>*__how>do', 'do_*__do_what__what>*__what>do']

5541_2.q What do you do between now and Wimbledon? What things do you work on?
['do_*__do_what__what>*__what>do', 'what>* work_*']

top responses:
3881_6.a No, it's me definitely. I'm really trying. That's one thing that I'm really trying to take more charge in the decision-making, you know. You have lots of people giving advices all the time. It just gets confusing. And I'm the one, you know, who knows how it felt to become No.1, to win Grand Slam. So I really try to look back to that time and reflect what I was doing then, comparing to what I was doing now. And I saw some differences. So I really tried to step up and, you know, work hard and push myself and surround myself with good people.
["'s_* 's_definitely 's_no no>*", "trying_'m trying_* trying_really", "'s_* 's_know", 'have_*', 'gets_* gets_confusing gets_just', "'m_* and>*", 'so>* try_* try_look try_really try_so', 'and>* saw_*', 'push_* so>* surround_* surround_with tried_* tried_really tried_so tried_step work_* work_hard work_know']

4214_9.a Well, I mean, it was a good win obviously, and we worked on some things before coming here. Just been trying to put them into the matches little by little. This week was a good start. You know, yeah, just try and keep building on that going into the stretch over in the States. Because it's a very important period for me, this one coming up, because I struggled there the last couple years. Good chance for me to get some matches and hopefully play well there, because the surface should suit me over there. It's just I struggled the last couple years there. Getting over there early, get some good practice in.
['was_* was_mean was_obviously was_well well>* worked_* worked_before worked_on', 'just>* just>been trying_* trying_been trying_just trying_put', 'was_*', 'keep_* keep_on try_* try_just try_know try_yeah', "'s_* 's_because 's_coming because>*", '', "'s_* 's_struggled", 'get_* get_getting get_in getting>* getting>over']

5842_9.a I bring my own hitting partners, different kinds, and I work with my team. They try to play different styles. That's their job. (Laughter.)
['bring_* work_* work_with', 'try_* try_play', "'s_*", '']

111_1.a Well, yeah, I try to concentrate against, especially first couple of games. I usually do well to break the games, you know, and I try to think a lot what did I do well, you know, these past couple sets and, you know, what did I do wrong and make sure that before I play first points on the third set that what I have to do is there. I don't know. Just fight again. That's the only important thing.
['try_* try_concentrate try_well try_yeah well>*', 'do_* do_break do_know do_usually do_well try_* try_know try_think', 'know_* know_do', 'fight_* fight_again fight_just just>*', "'s_*"]

1158_6.a Well, I wasn't born like that.  I keep working hard on all my strokes, my serve, my forehand.  I try to improve it day to day.
['born_* born_like born_was born_well well>*', 'keep_* keep_working', 'try_* try_improve']




1
top prompt:

,0,1,2,3,4,5,6,7,type_id
will>*,1.029253,0.532545,1.153288,1.282362,0.991471,1.335638,1.512199,1.106152,1.0
going_*__going_are,1.021476,0.592999,1.268010,1.304610,1.115215,1.279629,1.498275,1.178506,1.0
are>*__going_*,1.018917,0.593653,1.240439,1.298572,1.066024,1.293147,1.486427,1.176297,1.0
are_*__are_what,1.030714,0.594019,1.008208,1.338540,1.127179,1.420803,1.551720,1.017175,1.0
be_*__be_what,1.094220,0.599262,1.142316,1.287656,1.027747,1.246965,1.520386,1.010938,1.0

top response:

,0,1,2,3,4,5,6,7,type_id
have_'ll,1.081366,0.672651,1.094378,1.260036,1.113196,1.343347,1.566586,0.956881,1.0
have_hopefully,1.033055,0.725882,1.191892,1.187055,1.164994,1.125782,1.537591,1.062537,1.0
'm_yet,1.074761,0.733070,1.270383,1.236572,1.094308,1.051111,1.488099,1.045396,1.0
'm_worried,1.078581,0.769510,1.244417,1.164254,1.016196,1.077727,1.463963,1.045015,1.0
take_will,0.820443,0.777609,1.284624,1.265605,1.041802,1.174257,1.420946,1.139167,1.0

top prompts:
6071_1.q You have been working with Thomas Enqvist for a couple of months now. What are your thoughts on your cooperation so far? Will you continue to work together throughout the year?
['are_*__what>*', 'will>*']

3880_19.q Will there be lots more Grand Slam champions out of China in tennis now, do you think?
['think_*__think_be__think_do will>*']

5213_7.q What are your plans for offseason? Any vacation? Are you going to the Davis Cup final? Any plans on that?
['are_*__what>*', '', 'are>*__going_*', '']

3720_11.q We know how tough David Ferrer can be. Are you going to try to do some things differently against him? What are your thoughts on that matchup?
['are>*__going_*', 'are_*__what>*']

6183_7.q Are you going to stay on in Paris for a little bit? What are your plans for the grass season?
['are>*__going_*', 'are_*__what>*']

top responses:
4347_5.a No, because I already achieved my goal. I would love to finish No.1 as well for the end of the year. For that it's going to take a great stretch again, winning Basel, Paris and London I assume to give myself a chance. We'll see how it goes. Look, I'm relaxed about it. I'll give everything I can. I want to get through this season well and finish strong. But it's not the number one goal right now. Right now it's to manage my schedule, hopefully be in good shape for Basel, then kind of go from there. Just to repeat, the goal was to become world No.1 this year, which happened, not the end of the year. But if that happens, that's a bonus.
['no>* no_* no_achieved', 'love_* love_finish love_would', "assume_* assume_give for>* going_'s going_* going_for going_take going_winning", "see_'ll see_* see_goes", "'m_* 'm_look 'm_relaxed look>*", "give_'ll give_*", 'want_* want_get', "'s_* 's_not 's_now but>*", "be_'s be_* be_go be_hopefully be_in be_then right>*", 'just>* just>to was_* was_become was_repeat', "'s_* 's_happens but>* but>if"]

2930_14.a I mean, I hope so. I mean, I want to think that can happen again. But, yeah, you're right. Everyone has one Cinderella story, and mine was last year. Now it's like everyone just expects me to do that because I did it last year. But that doesn't necessarily mean that it's going to happen. I mean, I'm going to have to play well. It's not just going to happen for me. I'm gonna have to play well and fight hard like I did last year, and, um, hopefully it will be good for me and I'll be the better player out there.
['hope_* hope_mean hope_so', 'want_* want_mean want_think', "'re_* 're_right 're_yeah but>*", 'has_* was_*', "'s_* 's_like 's_now expects_* expects_did expects_do expects_just now>*", 'but>* mean_* mean_does mean_going mean_necessarily', "going_'m going_* going_have going_mean", "going_'s going_* going_happen going_just going_not", "be_* be_for be_good be_hopefully be_um be_will gon_'m gon_* gon_have", "and>* be_'ll be_* be_there"]

4967_17.a I'm pretty sure it's going to be pretty fair. I mean, it's going to be pretty even. I'm sure they'll be cheering for both of us. Everyone will be cheering our winners and whatnot. It's really going to be a victory for everybody in the crowd if we play each other. They'll have a Canadian in the final. It would be a fun match to play and a good atmosphere, for sure. Maybe somebody will have more of the support. I hope it would be me if that was the case, but we'll see (smiling).
["'m_* 'm_sure", "going_'s going_* going_be going_mean", "'m_* 'm_sure", 'cheering_* cheering_be cheering_will', "going_'s going_* going_be going_play going_really", "have_'ll have_*", 'be_* be_for be_would', 'have_* have_maybe have_will maybe>*', "hope_* hope_be see_'ll see_* see_smiling"]

6055_1.a Well, I would love to win those matches in two sets, but I always feel like I put in the work to be ready to play whatever it takes. If it takes three hours to win the match in three sets, I will be ready for that. If I have a match that's easier and a more convincing win, then I will take that, as well. But I will do whatever it takes. If I don't start good, if I lose the first set, I'm going to be there until the end.
['feel_* feel_always feel_put love_* love_well love_win love_would well>*', 'be_* be_ready be_takes be_will if>*', 'if>* take_* take_have take_then take_well take_will', 'but>* do_* do_takes do_will', "going_'m going_* going_be going_lose going_start if>*"]

546_5.a I will do anything I can, anything, to be able to not just beat Serena, but to win Wimbledon. I will do anything to win Grand Slams. I'm going to work hard. This just gives me extra motivation. Something that I look and I see that somebody's raising the level, and that's where I want to get to. To be able to raise my level even higher against top opponents.
['do_* do_be do_will', 'do_* do_will do_win', "going_'m going_* going_work", 'gives_* gives_just', '', "'s_* 's_want and>* see_* see_raising", 'be_* be_able be_to to>*']




2
top prompt:

,0,1,2,3,4,5,6,7,type_id
think_*__think_what,1.197465,1.046705,0.670099,1.291630,1.045561,1.467219,1.330959,0.945044,2.0
have>*__played_*__played_have,1.156198,1.138160,0.675621,1.312374,1.293401,1.258340,1.252053,1.210052,2.0
played_*,1.178912,1.191127,0.679990,1.308993,1.325899,1.257607,1.211431,1.227966,2.0
think_*__what>*,1.213091,1.056169,0.682394,1.306610,1.083586,1.480133,1.323852,0.956038,2.0
think_*__think_of__think_what,1.215357,1.096311,0.689644,1.305629,1.028032,1.430720,1.270178,0.955797,2.0

top response:

,0,1,2,3,4,5,6,7,type_id
won_*,1.258377,1.196535,0.558545,1.285411,1.246320,1.287155,1.200692,1.188083,2.0
won_mean,1.205385,1.143031,0.562176,1.258819,1.255426,1.205559,1.334921,1.057083,2.0
won_know,1.223428,1.232449,0.585416,1.242030,1.263787,1.247248,1.207182,1.150428,2.0
won_in,1.259561,1.199660,0.612412,1.269198,1.275801,1.204014,1.205743,1.195606,2.0
know_well,1.165847,1.012158,0.623633,1.232463,1.062415,1.381328,1.374095,0.911233,2.0

top prompts:
1622_5.q How big is the difference between this sort of match, you've been playing a lot of futures match, but I don't know how many challengers you've been playing, and a junior Grand Slam, for instance?
['how>*__know_* how>*__playing_* know_*__know_do playing_*__playing_is']

5427_16.q What do you know of her as a player and how would you describe your respective styles?
['describe_*__describe_how know_*__know_do__what>*']

6432_5.q You were playing tennis way above your ranking in the first set. Have you ever played that level before, and do you think you can now start playing that level consistently?
['have>*__played_*__played_have played_*__played_before__played_have think_*__think_do']

3111_8.q From your matches earlier, what do you remember from those matches?
['from>* remember_*__remember_what']

1778_15.q What do you make of the notion that squash shots are occasionally being played or shots that come out of the squash game are being played today?
['played_* what>*__what>do']

top responses:
2458_7.a I don't know. She has a great serve on grass, so obviously that helps. I should have won more than twice here, but I didn't. And hopefully I can rectify that this year.
['know_* know_do', 'has_* helps_* helps_obviously', 'did_* won_* won_have won_here won_should won_twice', 'and>* and>hopefully rectify_* rectify_can rectify_hopefully']

1735_9.a Well, it says a lot about her. I mean, she's won five Wimbledons now. She's beaten me on grass now, so that definitely says a lot.
['says_* says_well well>*', "won_'s won_* won_mean won_now", "beaten_'s beaten_* beaten_now beaten_on beaten_says"]

4451_5.a Well, first of all, if you look at our record it says it all. I mean, I haven't won in any last meetings, so I definitely need to find something to surprise her tomorrow, because she's in a great form, you know, feeling really confident right now. You know, she has everything on her side.
['says_* says_first says_look says_well well>*', "need_'s need_* need_definitely need_find won_* won_have won_in won_mean", 'has_* has_know']

5213_1.a I played Serena, and I know that she's in great form now. I didn't have any chance to her. She has a big serve, everything, and I think that she likes to play the finals. About Li Na, I mean, she's great person, and she played really great here. She won all matches in the group. She beat today in semifinal. I think that she's very solid from the basic line. She can play down the line, cross, she's moving very well, she's going for the volleys, too, so she's very consistent player, I think.
["know_'s know_* played_*", 'have_* have_did', 'has_* think_* think_likes', "'s_* 's_about 's_mean about>* played_* played_great played_here", 'won_* won_in', 'beat_* beat_in', "think_'s think_*", 'think_* think_going']

4191_0.a I don't think so. Every single match every week is won on the basis of hard work.
['think_* think_do think_so', 'won_* won_is won_on']




3
top prompt:

,0,1,2,3,4,5,6,7,type_id
been_*__been_has,1.154575,1.274408,1.130674,0.436758,1.096999,1.095909,1.290464,1.026623,3.0
been_*,1.153646,1.269146,1.159866,0.454188,1.052782,1.204385,1.238575,1.107916,3.0
been_*__what>*,1.116167,1.220201,1.208998,0.481859,1.095586,1.181512,1.281500,1.121013,3.0
been_*__have>*,1.093404,1.215954,1.179324,0.491063,0.962101,1.219532,1.249094,1.098328,3.0
been_*__been_has__been_there,1.108008,1.257066,1.147437,0.502284,1.116277,1.185385,1.279214,1.087618,3.0

top response:

,0,1,2,3,4,5,6,7,type_id
been_always,1.157884,1.222840,1.166764,0.588508,1.167690,1.243089,1.313821,1.140989,3.0
been_great,1.163742,1.210095,1.173097,0.590712,1.175477,1.215457,1.319810,1.167590,3.0
been_with,1.142550,1.218397,1.184616,0.597394,1.173116,1.223021,1.303265,1.165604,3.0
been_really,1.158042,1.221788,1.193701,0.603344,1.167613,1.218293,1.299536,1.173653,3.0
been_just,1.156198,1.239690,1.208971,0.604555,1.197551,1.201427,1.282709,1.199582,3.0

top prompts:
6243_3.q You have a Chinese sponsor, Li Ning. How has that been after winning the Open? Have there been a lot of activities, more so than you might have had to do a couple years ago?
['been_*__been_has__how>* how>*__how>has', 'been_*__been_there been_*__have>*']

2026_7.q What have the demands on your time been like since Sports Illustrated? Obviously that's a very high profile thing to be in. Has that changed your life a lot or at all?
['been_*__been_have been_*__what>*', 'changed_*__changed_has has>*']

5709_2.q A lot of players have found it difficult to refind the consistency after their first Grand Slam title. What has been difficult for you? What have been the challenges? Has Novak been able to give you any advice to see you through this period?
['been_*__been_for been_*__been_has__what>* been_*__been_what__what>* what>*__what>has', 'been_*__been_have been_*__been_what__what>* what>*__what>have', 'been_*__been_able been_*__been_has__has>*']

3897_6.q Li Na being the first Asian Grand Slam winner, has that been an inspiration to you?
['been_*__been_has']

5574_7.q Right up until tonight's game, has your campaign over the past two weeks been as good of tennis as you've been playing in your career?
['been_*__been_has']

top responses:
173_1.a She's been great. It's really cool having the perspective of someone who has gone through it, and also someone who plays similar to me. So just having her guidance has been really helpful. Yeah, we've just been practicing a lot, staying low, working on movement, and I think it kind of showed today.
["been_'s been_* been_great", "'s_* 's_cool 's_having", 'been_* been_has been_having been_helpful been_so so>* so>just', "practicing_'ve practicing_* practicing_been practicing_just practicing_staying practicing_yeah think_* think_showed yeah>*"]

1769_14.a No, I mean, it hasn't been that difficult for me at all. I think a lot of my frustrations in the past came from poor concentration. I think because I spent so much time at the courts, you know, around tennis, around tennis tournaments, you know, my mind got a little bit sort of, I don't know, a little bit tired of being on the court. And now, like I said, I'm spending less time around the courts. I'm spending less time watching tennis on the TV and having more of a life outside tennis, which is what's, for me, making a difference. I'm enjoying myself when I'm on the court now rather than it being a bit of a drag.
['been_* been_all been_difficult been_for been_has been_mean been_no no>*', 'think_* think_came', 'think_* think_got', "and>* and>now spending_'m spending_* spending_now spending_said", "spending_'m spending_* spending_is spending_watching", "enjoying_'m enjoying_*"]

3217_10.a We haven't worked together yet, so it's no different than normal. More so than that, we've been friends for a long time.
["'s_* 's_different 's_so worked_* worked_have worked_together worked_yet", "been_'ve been_* been_for been_so more>*"]

4813_1.a Oh, it's been great. Yeah. It's good.
["been_'s been_* been_great been_oh oh>*", 'yeah>* yeah_*', "'s_* 's_good"]

2462_3.a Well, he has always been very aggressive. But now he's making less unforced errors, I guess.
['been_* been_aggressive been_always been_has been_well well>*', 'but>* but>now guess_* guess_making']




4
top prompt:

,0,1,2,3,4,5,6,7,type_id
say_*__say_did__what>*,1.055753,1.105856,1.172143,1.064950,0.541020,1.362242,1.036849,1.121043,4.0
say_*__say_to__say_what__what>*,1.065160,1.122508,1.180323,1.025560,0.543373,1.350329,1.045646,1.097821,4.0
say_*__say_did__say_to__say_what__what>*,1.063010,1.130922,1.184778,1.044063,0.558098,1.348753,1.012438,1.135273,4.0
say_*__what>*,1.039548,1.075040,1.091245,1.053678,0.559151,1.382721,1.125849,1.048972,4.0
talk_*__talk_did,1.041667,1.153686,1.140871,1.014077,0.566663,1.426454,1.008444,1.090276,4.0

top response:

,0,1,2,3,4,5,6,7,type_id
asked_*,1.087368,1.111035,1.144027,1.034541,0.547727,1.415786,1.069267,1.140354,4.0
sitting_*,1.087271,1.186492,1.214257,0.942601,0.560868,1.427531,1.008696,1.110207,4.0
oh>*,1.119154,1.096515,1.148108,1.029201,0.561440,1.354423,1.153463,0.966446,4.0
said_well,1.069284,1.134293,1.179574,1.083234,0.562052,1.345357,1.022609,1.131403,4.0
told_was,1.068833,1.189593,1.167921,1.069154,0.573050,1.397914,0.936245,1.139699,4.0

top prompts:
4063_10.q You didn't talk to her in Brisbane?
['talk_*__talk_did talk_*__talk_to']

1859_16.q Have you spoken to any of your Fed Cup teammates this week? And have they told you how they feel about you coming back into the tomorrow?
['spoken_*__spoken_have__spoken_to', 'and>* told_*']

3923_3.q Did you speak to him after it? Did you talk to David? Did he apologize?
['did>* speak_*', 'did>*__talk_* talk_*__talk_to', 'did>*']

5263_7.q Who did you talk to during the delay?
['talk_*__talk_did talk_*__talk_to who>*']

3321_7.q Did you talk to Victoria after the match yet? Have you had a chance to ask her what happened?
['did>*__talk_* talk_*__talk_to', 'had_*__have>*']

top responses:
3781_8.a No. He just asked me if it's the shoulder and I said yes. That's it.
['no>* no_*', "asked_'s asked_* asked_just", 'and>* said_* said_yes', "'s_*"]

4253_17.a No. I mean my coach he was always sitting alone, and my team, my father and my boyfriend and physio they were sitting in my chair and these three guys.
['no>* no_*', 'sitting_* sitting_in sitting_mean sitting_were']

5782_11.a No. I had no idea who I was playing for thins match actually. I went on the Tennis Channel set and Justin told me I was playing Halep and I was like Oh, Okay. I truly had not looked at the draw. It's not so much about my opponent for me, it's about my game.
['no>* no_*', 'had_*', 'told_* told_playing went_* went_on', 'and>* was_* was_like', 'oh>* oh_*', 'okay>* okay_*', 'looked_* looked_at looked_had looked_not looked_truly', "'s_'s 's_* 's_about"]

1075_3.a Yeah, I heard about him.  Like first I heard his name after Washington, then I saw him playing doubles in Cincinnati and singles in New Haven. I asked some things from his opponent, the guys who played him, like how is he playing.  I saw only one match.
['heard_* heard_about heard_yeah yeah>*', 'like>* saw_* saw_heard saw_playing saw_then', 'asked_* asked_from asked_like', 'saw_*']

1509_2.a Yeah, the physios told us maybe 15 to 20 players have almost the same thing as me. So they ask us to really wash even more our hands, to didn't touch the same food as the other, didn't drink in the same water, to be really careful, because there is a virus going on, so...
['told_* told_have told_yeah yeah>*', 'ask_* ask_so ask_wash so>*']




5
top prompt:

,0,1,2,3,4,5,6,7,type_id
feel_*__feel_now,1.099974,1.129066,1.239600,1.152036,1.289675,0.408886,1.314320,1.155465,5.0
feeling_*__feeling_are__how>*,1.176024,1.208878,1.206700,1.086709,1.312381,0.409343,1.260881,1.214859,5.0
do>*__feel_*__feel_do__feel_playing,1.146690,1.193027,1.152799,1.152215,1.346524,0.421844,1.322920,1.127076,5.0
feel_*__feel_do,1.104209,1.117418,1.203544,1.142313,1.265165,0.426570,1.373412,1.044297,5.0
feel_*__feel_do__how>*,1.190418,1.176945,1.124022,1.178440,1.381882,0.441167,1.298054,1.212602,5.0

top response:

,0,1,2,3,4,5,6,7,type_id
'm_physically,1.155682,1.143277,1.217395,1.125303,1.235212,0.474613,1.266853,1.146912,5.0
'm_tired,1.137926,1.125980,1.173303,1.148966,1.239097,0.508785,1.301687,1.113153,5.0
feel_physically,1.144334,1.177881,1.209186,1.123040,1.279970,0.513591,1.289905,1.150014,5.0
feel_confident,1.121190,1.164850,1.167346,1.159332,1.300933,0.515009,1.304628,1.136917,5.0
feel_good,1.144566,1.172629,1.182966,1.159265,1.282155,0.527436,1.289555,1.142724,5.0

top prompts:
343_2.q You have an extra difficult game where you have to use an extra spin of your game. So given the fact that you have to play some extra games  Nadal now is out, which gives you maybe an extra motivation. How do you feel? Do you feel extra motivated for the rest of the tournament?
['feel_*__feel_do__how>*', 'do>*__feel_*']

5188_0.q How do you feel? Watching the Australian Open it was very scary watching your ankle buckle. How does your ankle feel now?
['feel_*__feel_do__how>*', 'feel_*__feel_does__feel_how feel_*__feel_now__how>*']

15_2.q Physically and mentally do you feel okay?
['feel_*__feel_do feel_*__feel_physically physically>*']

2308_4.q You played two and a half hours two days ago, two hours fifteen minutes today. Aggressive tennis. Physically do you feel fine?
['feel_*__feel_do feel_*__feel_physically physically>*']

4595_2.q Is that the longest match of your career? How are you feeling physically now?
['is>*', 'feeling_*__feeling_are__feeling_now feeling_*__feeling_are__how>* feeling_*__feeling_physically']

top responses:
1883_1.a I don't feel better today than the first day or the second. I think I was feeling the same in the three matches. I'm feeling good. I'm feeling the ball and feeling my legs good also. You know, I pretty feel good in all the matches, in the three matches the same, more or less.
['feel_* feel_better feel_do feel_than', 'think_* think_feeling', "feeling_'m feeling_* feeling_good", "feeling_'m feeling_* feeling_also feeling_good", 'feel_* feel_good feel_in feel_know feel_pretty']

3454_5.a No, I wasn't feeling that bad. I feel always bad pulling out of the match, because then I think that -- I don't know. I feel bad pulling out.
['feeling_* feeling_bad feeling_no feeling_was no>*', 'feel_* feel_always feel_bad feel_pulling feel_think', 'feel_* feel_bad feel_pulling']

6292_13.a I don't know. I've been feeling really well on hard court this year. I don't know, I'm just really happy about it. At least I feel good on some surface this year. I don't know really know. I just feel comfortable.
['know_* know_do', "feeling_'ve feeling_* feeling_been feeling_on feeling_well", 'know_* know_do', "'m_* 'm_happy 'm_just", 'at>* feel_* feel_good feel_least feel_on', 'know_* know_do know_know', 'feel_* feel_comfortable feel_just']

404_0.a I was feeling way worse in the first set. I was really sore everywhere and I was trying to convince myself that it should get better. And it did. Now I feel quite good actually, which is surprising me.
['feeling_* feeling_in feeling_was feeling_worse', 'was_* was_everywhere was_sore', 'and>* trying_* trying_convince trying_was', 'and>* did_*', 'feel_* feel_actually feel_good feel_is feel_now now>*']

3304_1.a To be honest, it feels good. You know, that's something that I'm happy about, is my condition. I haven't felt any pain in my shoulder. I've been feeling well on the court. Obviously, I feel a little bit exhausted, you know, because the match was almost three hours. It's normal. But I think I'm physically fit. And I just need to get some things better in my game for the next challenge.
['feels_* feels_be feels_good to>*', "'s_* 's_know is_*", 'felt_* felt_have', "feeling_'ve feeling_* feeling_been feeling_on feeling_well", 'feel_* feel_exhausted feel_know feel_obviously feel_was obviously>*', "'s_* 's_normal", "but>* think_'m think_*", 'and>* need_* need_get need_just']




6
top prompt:

,0,1,2,3,4,5,6,7,type_id
was_*,1.110050,1.489184,1.158403,1.239469,1.086001,1.336831,0.347455,1.371045,6.0
was_*__what>*,1.089684,1.455052,1.173272,1.261514,1.070273,1.346836,0.355167,1.403520,6.0
was_*__was_what,1.081862,1.449563,1.176958,1.239616,1.033535,1.359986,0.359882,1.392840,6.0
was_*__was_what__what>*,1.087176,1.448471,1.174467,1.260128,1.056595,1.348275,0.363705,1.402448,6.0
were_*,1.101461,1.442414,1.157626,1.238660,0.984888,1.354865,0.393764,1.371292,6.0

top response:

,0,1,2,3,4,5,6,7,type_id
was_just,1.088369,1.454979,1.250559,1.193605,1.033478,1.309714,0.407539,1.378404,6.0
was_actually,1.103721,1.439569,1.192116,1.176255,0.951562,1.354406,0.414391,1.344319,6.0
was_yeah,1.143058,1.465070,1.164378,1.250613,1.109954,1.339046,0.423675,1.390772,6.0
gave_*,1.126723,1.460922,1.183128,1.199738,1.061919,1.282884,0.432826,1.424482,6.0
was_mean,1.144432,1.468158,1.178777,1.225420,1.079049,1.287545,0.433126,1.350299,6.0

top prompts:
1226_7.q Youzhny is a player with a lot of big wins.  He's won against Nadal, won against Federer.  Was it a sufficient match, and what was the approach for you before you went into the game?
['was>* was_*__was_what']

3419_4.q You somehow changed your game towards the end. Was it what your coach that told you to change it?
['was>* was_*__was_what']

3726_12.q Then your reaction at the end of the match, what was your feeling? Was it happy? Relief? A little bit of unhappiness because you almost let it go?
['was_*__was_what', 'was>*', '', '']

1984_8.q Was it mental or what was it?
['was>* was_*__was_what']

5869_5.q How much were you following the US Open at all? What was your reaction to seeing Marin and Kei in the final? Was the result surprising to you?
['how>*', 'was_*__was_what__what>*', 'was>*']

top responses:
2850_8.a Actually, September 1st was the first day back to school, and I missed it (smiling). But it started already. So my friends attended some classes already, but without me.
['actually>* missed_* missed_smiling was_* was_actually', 'but>* started_* started_already', 'attended_* attended_already attended_so so>* without_*']

3910_2.a It's the first match in Wimbledon this year. First official match that I had on grass. So, you know, it took some time to get adjusted. But all the credit to him for serving the first set the way he did. It was really hard because he had a really high percentage of first serves. But that break on 4-All was a turning point. I think was crucial. Was important to start off with a set advantage.
["'s_*", '', 'so>* took_* took_adjusted took_know took_so', '', 'was_* was_had was_hard', 'but>* was_*', 'think_* think_was', 'was>* was_* was_important was_start']

4739_8.a Yeah, but actually I only took one medical timeout. You know, it took a little bit maybe more time because they were evaluating that. But I took only one medical timeout. And my knee, I slipped. Was it, I don't know, maybe third game of the second set. So it was a little bit bothering me. But it wasn't that big of a deal. It was just my back that caused my...
['yeah>* yeah_*', 'but>* but>actually took_* took_actually took_only', 'took_* took_evaluating took_know', 'but>* took_*', 'and>* slipped_*', 'was>* was_*', 'know_* know_do', 'so>* was_* was_bothering was_so', 'but>* was_* was_big', 'was_* was_caused was_just']

3118_10.a You guys gave Henman a hard time up until he was three years retired. You're forgetting you're trying to tell me a story, but I was actually there for the Henman years.
['gave_* gave_up gave_was', "forgetting_'re forgetting_* forgetting_trying was_* was_actually was_for was_there"]

1123_1.a No.  It was a little tight because when I was -- no, when you receive a ball at 120 miles, you get some shock into the wrist, which I'm not used to because I'm not playing against girls every day hitting the balls like this.
['no>* no_*', 'was_* was_get was_tight']




7
top prompt:

,0,1,2,3,4,5,6,7,type_id
do>*__think_'s__think_*,1.155789,0.996740,1.013655,1.067685,1.062727,1.260903,1.513347,0.531644,7.0
is>*,1.062490,1.067104,1.080466,1.062832,1.071693,1.189330,1.466067,0.538167,7.0
think_'s__think_*,1.169565,0.959485,1.010322,1.085590,1.038018,1.252852,1.516804,0.552625,7.0
like_*__like_do,1.071264,0.986405,1.009678,1.153968,1.063828,1.215064,1.495786,0.581972,7.0
is_*__is_like,1.128784,1.161261,1.067291,0.934017,1.014746,1.132462,1.387028,0.589775,7.0

top response:

,0,1,2,3,4,5,6,7,type_id
think_is,1.129770,1.083397,0.934999,1.095067,1.139335,1.220646,1.479282,0.544207,7.0
is_there,1.125157,1.102398,1.057348,1.093204,1.092229,1.258255,1.426755,0.552333,7.0
think_are,1.147441,1.094366,0.939655,1.069253,1.088532,1.184831,1.462403,0.561257,7.0
think_'s,1.135482,1.098581,0.953449,1.067127,1.089396,1.259378,1.460707,0.574519,7.0
's_about,1.088023,1.117607,1.035078,1.076636,1.064573,1.207458,1.427095,0.577848,7.0

top prompts:
6218_1.q Do you think it's just confidence? Is that something that confidence can do in those big moments?
["do>*__think_'s__think_*", 'is>*']

1802_3.q It's obviously very entertaining to watch slices, lobs and dropshots. Do you think it's possible to do that against some of the players you might face later? Is that just a one-off today?
["do>*__think_'s__think_*", 'is>*']

1389_5.q The crowd likes you very much because not only do you play great tennis, but also you have the quality of being able to have fun and joke on the court. But now you seem more calm. Is it because you really want to focus and be the best in tennis? Do you think it's sort of a better discipline?
['is>*', "do>*__think_'s__think_*"]

5447_2.q I know that injuries are a personal thing. There's been a big trend of people pulling out today. Do you think it's something about the surface? Is this all just a coincidence?
["do>*__think_'s__think_*", 'is>*']

4898_10.q Do you think it's about patience during rallies? Is that something you learned over your career?
["do>*__think_'s__think_*", 'is>*']

top responses:
5050_10.a If that's one of the options. You know, I don't think it's really necessary. I think what's necessary is that we consider all different sides of that rule that was implemented this year on the tour. I understand that they want to be more strict on the rule. That's why they came up with that. I respect that. No problem. I'm probably one of the few players that they are looking carefully and see how much time I spend on the court. I know that I maybe take more time than some other players. But as much as you know it's fair and you have this prewarning, I have no problem with it.
["'s_* 's_if if>*", "think_'s think_* think_do think_know", 'think_* think_is', 'understand_* understand_want', "'s_* 's_came", 'respect_*', '', "'m_* 'm_looking 'm_probably", 'know_* know_take', "but>* but>as have_'s have_*"]

5608_13.a This is a big test for me. I don't need Murray to have a further test. The draw is a very testing draw. I know it's tough. It's not easy for anybody right now at this stage of the tournament, because you don't want to have any hiccups right now. I hope I can continue playing at a high level. What I've shown over the last three to four months to myself is that I'm more confident, that I know I'm most likely going to play okay in my next match, which wasn't always the case midway through last year when I didn't know how I was going to feel actually during the match. I feel like I can think ahead. I can think tactics. I can think many things out there. Everything else but my body, and that's very positive. I've overcome a lot in the last few months.
['is_*', 'need_* need_do need_have', 'is_*', "know_'s know_*", "'s_* 's_at 's_easy 's_for 's_not 's_now 's_want", 'hope_* hope_continue', "is_'m is_* is_shown what>*", 'know_* know_going know_that that>*', 'feel_* feel_think', 'think_* think_can', 'think_* think_can think_there', '', "overcome_'ve overcome_* overcome_in"]

5659_10.a Uhm, not necessarily, you know. What's interesting about the bigger guys these days is that they play from the baseline. Whenever you were over 185, you used to serve and volley back in the day because you would take advantage of your size, of your power. And now it's all these guys over 190 are actually playing further back in the court because they have more time, their serve is as big as it is, and they don't need to kill themselves always running back and forth over hours and hours. That I think is something that has really changed. And, of course, when you're tall like this, the serving, it helps the serving. But, you know, I don't think it's impossible for a smaller guy to succeed in today's game. I mean, Rafa, me, we're not the tallest out there. We're the norm, let's say. And that works perfectly well. But, of course it is good to I guess be over 180. It just seems like it. But nevertheless I still believe you can do very well at 175, 180 as well.
['know_* know_uhm uhm>*', "is_'s is_* is_play what>*", 'used_* used_serve used_take used_were whenever>*', "and>* and>now is_'s is_* is_big need_* need_do need_kill", 'think_* think_is', "and>* helps_'re helps_* helps_of", "but>* think_'s think_* think_do think_know", "'re_* 're_mean 're_not 're_there", "let_'re let_* let_say", 'and>* works_* works_well', 'but>* is_* is_good is_of', 'be_* be_guess', 'seems_* seems_just seems_like', 'believe_* believe_do believe_nevertheless believe_still but>* but>nevertheless']

3171_6.a I always wish for Serena to play all the events because I think she's great for women's tennis. She's a great player, she's a great athlete. We all respect her a lot. But I think there is a very tough draw. Women's side is very strong at the moment. There are so many players that can go very far in the tournaments, and you can never predict it. I think this kind of challenge makes women's tennis very interesting. You know, even if Serena is not here, I really think there are so many great players out there. It is still a great competition.
['wish_* wish_always wish_play wish_think', "'s_'s 's_*", 'respect_*', 'but>* think_* think_is', 'is_* is_at is_strong', 'are_* are_there predict_* predict_can predict_never there>*', 'think_* think_makes', 'think_* think_are think_is think_know think_really', 'is_* is_still']

4972_5.a I always say the same. I don't like to be arrogant. I don't like to talk about a part of the history of tennis where I am involved because going to sound very arrogant if I say this era is great. A lot of eras are good. We had a lot of fantastic years in tennis. I think this era is special because the best players of the world, they have the ability to be in the final rounds of most of the tournaments. That's create a classic matches, good battles. But at the end there is very qualified people from the press, from past players, can analyze much better this era than me that I'm inside, that I'm involved in.
['say_* say_always', 'like_* like_be like_do', 'like_* like_do like_talk', 'are_* are_good', 'had_* had_in', 'think_* think_is', "create_'s create_*", "analyze_'m analyze_* analyze_better analyze_can but>* but>at is_* is_at is_from is_there"]

### transforming the entire corpus

In [21]:
corpus = pt.transform(corpus)

In [22]:
utt1 = corpus.get_utterance('2020_8.q')

In [23]:
utt1.text

"On a physical level, you're stronger maybe than ever. How do you work hard if the tournament is so close? What do you do in the gym? How do you keep the regimen going on?"

In [24]:
utt1.get_info('prompt_types__prompt_type.8')

0.0

## Storing models

In [25]:
import os

In [26]:
pt.dump_model(os.path.join(ROOT_DIR, 'pt_model'))

dumping embedding model
dumping training embeddings
dumping type model 8

In [27]:
new_pt = PromptTypes(prompt_field='question_motifs', ref_field='arcs_censored', 
                 prompt_filter=question_filter, ref_filter=response_filter,
                 prompt_transform_field='question_motifs__sink',
                 output_field='prompt_types_new', prompt__tfidf_min_df=50,
                 ref__tfidf_min_df=50, 
    random_state=1000, verbosity=1)

In [28]:
pt_model_dir = os.path.join(ROOT_DIR, 'pt_model')
!ls $pt_model_dir

km_model.8.joblib	   svd_model.joblib	   train_ref_ids.npy
prompt_df.8.tsv		   train_prompt_df.8.tsv   train_ref_vects.npy
prompt_tfidf_model.joblib  train_prompt_ids.npy    U_prompt.npy
ref_df.8.tsv		   train_prompt_vects.npy  U_ref.npy
ref_tfidf_model.joblib	   train_ref_df.8.tsv

In [29]:
new_pt.load_model(pt_model_dir)

loading embedding model
loading training embeddings
loading type model 8

In [30]:
utt = new_pt.transform_utterance(utt)

In [32]:
utt.get_info('prompt_types_new__prompt_type.8')

5.0

## Changing the number of types

In [35]:
pt.refit_types(4)

fitting 4 prompt types

In [47]:
for i in range(4):
    print(i)
    pt.display_type(i, type_key=4, k=5)
    print('\n\n')

0
top prompt:

                           0         1         2         3  type_id
will>*              0.630950  1.298031  1.065377  1.418889      0.0
are>*__going_*      0.679646  1.262736  1.145024  1.406238      0.0
are_*__are_what     0.686385  1.343151  0.991287  1.467312      0.0
going_*__going_are  0.690053  1.251750  1.158506  1.423621      0.0
going_*             0.706212  1.269886  1.170854  1.368935      0.0

top response:

                       0         1         2         3  type_id
take_will       0.725783  1.161619  1.122077  1.345260      0.0
know_yet        0.739357  1.295608  1.023017  1.251791      0.0
have_'ll        0.749098  1.289240  0.960487  1.480158      0.0
will_*          0.785161  1.262358  1.010793  1.288739      0.0
have_hopefully  0.786720  1.110688  1.054252  1.460314      0.0

1
top prompt:

,0,1,2,3,type_id
do>*__feel_*__feel_do__feel_playing,1.170831,0.508297,1.120550,1.303392,1.0
feeling_*__feeling_are__how>*,1.177613,0.512859,1.191507,1.243356,1.0
feel_*__feel_do__how>*,1.167678,0.512973,1.191546,1.284891,1.0
feel_*__feel_now,1.107351,0.532761,1.152466,1.290330,1.0
feeling_*__how>*,1.212046,0.532931,1.227951,1.174939,1.0

top response:

                        0         1         2         3  type_id
feel_confident   1.135918  0.578863  1.127169  1.281757      1.0
'm_physically    1.128963  0.581577  1.130372  1.243505      1.0
feel_physically  1.152812  0.583199  1.137885  1.266194      1.0
feel_good        1.147258  0.594057  1.132743  1.265594      1.0
feels_yeah       1.203118  0.597427  1.026486  1.326435      1.0

2
top prompt:

                                0         1         2         3  type_id
do>*__think_'s__think_*  1.004293  1.195127  0.598695  1.435172      2.0
think_'s__think_*        0.981542  1.197007  0.609744  1.435120      2.0
think_*__think_do        0.935450  1.225525  0.627383  1.424596      2.0
is_*__is_like            1.111017  1.074835  0.628596  1.316906      2.0
is>*                     1.026136  1.131318  0.630521  1.394571      2.0

top response:

                  0         1         2         3  type_id
think_is   1.060018  1.142320  0.611579  1.409632      2.0
think_are  1.066465  1.114231  0.612049  1.389874      2.0
think_'s   1.060338  1.174667  0.629274  1.386505      2.0
is_there   1.073984  1.184221  0.643225  1.359634      2.0
think_now  0.976245  1.106304  0.644016  1.384676      2.0

3
top prompt:

                                0         1         2         3  type_id
was_*__was_what          1.295417  1.241937  1.300852  0.428956      3.0
was_*__what>*            1.304098  1.228490  1.314929  0.437765      3.0
was_*__was_what__what>*  1.297477  1.230933  1.312691  0.439647      3.0
were_*                   1.288189  1.243271  1.277479  0.440140      3.0
was_*                    1.335885  1.213531  1.286668  0.445144      3.0

top response:

                      0         1         2         3  type_id
was_actually   1.290001  1.245703  1.251458  0.445544      3.0
was_just       1.308849  1.208106  1.294344  0.471725      3.0
took_so        1.248846  1.235757  1.286594  0.484393      3.0
gave_*         1.313197  1.169273  1.330380  0.488466      3.0
was_surprised  1.299895  1.245011  1.271755  0.492075      3.0

## Example variation: using arcs instead of motifs

In [44]:
pt_arcs = PromptTypes(prompt_field='arcs_censored', ref_field='arcs_censored', 
                 prompt_filter=question_filter, ref_filter=response_filter,
                 prompt_transform_field='arcs_censored',
                 output_field='prompt_types_arcs', prompt__tfidf_min_df=50,
                 ref__tfidf_min_df=50, n_types=4,
    random_state=1000, verbosity=1)

In [45]:
pt_arcs.fit(corpus)

fitting 78215 input pairs
fitting ref tfidf model
fitting prompt tfidf model
fitting svd model
fitting 4 prompt types

In [46]:
for i in range(4):
    print(i)
    pt_arcs.display_type(i,  k=5)
    print('\n\n')

0
top prompt:

                    0         1         2         3  type_id
feel_does    0.665389  0.965880  1.331548  1.141363      0.0
feel_do      0.674004  1.103788  1.349711  1.085030      0.0
feel_now     0.702311  1.164617  1.280405  1.125567      0.0
feel_*       0.709954  1.191471  1.180174  1.217915      0.0
feeling_now  0.720253  1.154975  1.247254  1.152868      0.0

top response:

                   0         1         2         3  type_id
'm_fit      0.656866  1.124501  1.303152  1.183858      0.0
feels_good  0.675811  1.071909  1.271421  1.159534      0.0
feels_*     0.685173  1.041319  1.307112  1.151629      0.0
feels_yeah  0.693127  1.113668  1.293664  1.172959      0.0
feel_been   0.695478  1.137340  1.295989  1.192680      0.0

1
top prompt:

                 0         1         2         3  type_id
like_*    1.066842  0.592536  1.369603  0.930745      1.0
there>*   1.080142  0.608612  1.203342  1.065093      1.0
's_*      1.056124  0.616678  1.432085  0.859614      1.0
is>*      0.982752  0.618435  1.411804  0.963110      1.0
wonder_*  1.109403  0.626687  1.291283  0.964637      1.0

top response:

                     0         1         2         3  type_id
understand_*  1.058724  0.589922  1.250244  1.024241      1.0
like_do       0.998437  0.618985  1.370673  0.925776      1.0
think_do      1.075442  0.622273  1.307021  0.957153      1.0
respect_*     1.064281  0.626583  1.296694  0.978071      1.0
's_like       1.082253  0.633566  1.276810  1.043093      1.0

2
top prompt:

                 0         1         2         3  type_id
was_*     1.173871  1.256789  0.422653  1.369839      2.0
was>*     1.172642  1.250716  0.442740  1.372602      2.0
were_*    1.170927  1.227038  0.443781  1.349003      2.0
was_what  1.191153  1.272507  0.444555  1.357529      2.0
were_in   1.154412  1.246567  0.453565  1.358357      2.0

top response:

                     0         1         2         3  type_id
was_actually  1.180324  1.244486  0.464286  1.354411      2.0
was_yeah      1.192064  1.305419  0.478270  1.361170      2.0
was_just      1.157896  1.277145  0.481335  1.366745      2.0
was_really    1.156121  1.291358  0.483771  1.370890      2.0
was_there     1.161162  1.242514  0.486821  1.382533      2.0

3
top prompt:

                  0         1         2         3  type_id
are_what   1.232947  1.039911  1.451706  0.653125      3.0
expect_do  1.152844  1.033127  1.461430  0.659696      3.0
will>*     1.197333  1.060435  1.453046  0.663972      3.0
be_will    1.172330  1.108597  1.459242  0.682239      3.0
going_'re  1.149314  1.054815  1.458452  0.697464      3.0

top response:

                    0         1         2         3  type_id
see_'ll      1.100716  1.058801  1.395763  0.718711      3.0
have_'ll     1.187852  0.978814  1.476159  0.729195      3.0
see_happens  1.135575  1.113555  1.375629  0.743777      3.0
see_will     1.091617  1.055427  1.348109  0.745719      3.0
see_goes     1.092629  1.105348  1.381137  0.746129      3.0

In [54]:
df = pt.train_types[8]['prompt_df']

In [55]:
df[]

 7.0    17273
 6.0    13076
 1.0     8328
-1.0     7765
 4.0     5791
 5.0     4379
 2.0     4213
 3.0     1775
 0.0     1567
Name: type_id, dtype: int64

In [56]:
pt.display_type(7, corpus=corpus, k=15)

top prompt:

,0,1,2,3,4,5,6,7,type_id
do>*__think_'s__think_*,1.155789,0.996740,1.013655,1.067685,1.062727,1.260903,1.513347,0.531644,7.0
is>*,1.062490,1.067104,1.080466,1.062832,1.071693,1.189330,1.466067,0.538167,7.0
think_'s__think_*,1.169565,0.959485,1.010322,1.085590,1.038018,1.252852,1.516804,0.552625,7.0
like_*__like_do,1.071264,0.986405,1.009678,1.153968,1.063828,1.215064,1.495786,0.581972,7.0
is_*__is_like,1.128784,1.161261,1.067291,0.934017,1.014746,1.132462,1.387028,0.589775,7.0
like_*__like_do__like_what,1.158260,1.085909,1.073930,1.106000,1.081123,1.172475,1.445129,0.596329,7.0
think_*__think_is__think_why,1.106006,1.153582,1.005937,1.060637,1.031982,1.275838,1.354624,0.596931,7.0
like_*__what>*__what>do,1.067488,1.098119,1.102917,1.078895,1.039799,1.149338,1.420797,0.602374,7.0
's_*,1.058483,0.873674,1.098032,1.079070,0.990816,1.222524,1.540646,0.610405,7.0
like_*__like_do__what>*,1.079468,1.042654,1.095969,1.105133,1.049147,1.168217,1.453664,0.610522,7.0
is_*__is_there,0.986260,1.045329,1.127833,1.087018,1.047326,1.211213,1.465816,0.613890,7.0
think_*__think_is,1.186325,0.986570,0.907824,1.152997,1.116619,1.307818,1.509882,0.615838,7.0
is_*__is_for,1.190566,0.992071,1.127290,1.034119,1.144013,1.097222,1.515197,0.616270,7.0
like_*,1.129812,0.926792,1.002089,1.104161,0.988201,1.275984,1.486153,0.617546,7.0
is_*__is_like__is_what,1.146602,1.170889,1.111644,0.809243,1.035441,1.112956,1.412647,0.621029,7.0

top response:

,0,1,2,3,4,5,6,7,type_id
think_is,1.129770,1.083397,0.934999,1.095067,1.139335,1.220646,1.479282,0.544207,7.0
is_there,1.125157,1.102398,1.057348,1.093204,1.092229,1.258255,1.426755,0.552333,7.0
think_are,1.147441,1.094366,0.939655,1.069253,1.088532,1.184831,1.462403,0.561257,7.0
think_'s,1.135482,1.098581,0.953449,1.067127,1.089396,1.259378,1.460707,0.574519,7.0
's_about,1.088023,1.117607,1.035078,1.076636,1.064573,1.207458,1.427095,0.577848,7.0
think_always,1.160450,1.146366,1.056997,1.030997,1.148802,1.090964,1.443062,0.579397,7.0
's_really,1.102912,1.138633,1.041846,1.073410,1.062061,1.272286,1.408632,0.579524,7.0
are_*,1.150882,1.140159,0.990419,1.088843,1.123055,1.227889,1.412462,0.584224,7.0
's_for,1.174044,1.151047,0.933325,1.103528,1.145505,1.252021,1.403483,0.584919,7.0
's_have,1.134782,1.183457,1.011616,1.062724,1.103204,1.238154,1.378383,0.584923,7.0
's_not,1.121248,1.170900,1.003781,1.094955,1.087861,1.298379,1.375438,0.585668,7.0
's_think,1.127065,1.183724,1.019362,1.043311,1.108111,1.287153,1.379997,0.589185,7.0
's_just,1.097919,1.171168,1.109979,1.027126,1.053521,1.183444,1.388287,0.589448,7.0
's_like,1.069719,1.167637,1.092151,1.076979,0.978795,1.300280,1.327465,0.591062,7.0
think_have,1.146993,0.961116,0.936355,1.190764,1.179200,1.180443,1.525938,0.597726,7.0

top prompts:
6218_1.q Do you think it's just confidence? Is that something that confidence can do in those big moments?
["do>*__think_'s__think_*", 'is>*']

1802_3.q It's obviously very entertaining to watch slices, lobs and dropshots. Do you think it's possible to do that against some of the players you might face later? Is that just a one-off today?
["do>*__think_'s__think_*", 'is>*']

1389_5.q The crowd likes you very much because not only do you play great tennis, but also you have the quality of being able to have fun and joke on the court. But now you seem more calm. Is it because you really want to focus and be the best in tennis? Do you think it's sort of a better discipline?
['is>*', "do>*__think_'s__think_*"]

5447_2.q I know that injuries are a personal thing. There's been a big trend of people pulling out today. Do you think it's something about the surface? Is this all just a coincidence?
["do>*__think_'s__think_*", 'is>*']

4898_10.q Do you think it's about patience during rallies? Is that something you learned over your career?
["do>*__think_'s__think_*", 'is>*']

5599_3.q Is it the same hip issue you had at Wimbledon? Do you think it's the same area?
['is>*', "do>*__think_'s__think_*"]

3414_11.q How important talent in tennis is? Do you think it's most important thing, or it just can carry you for a certain amount of distance?
['how>*__is_*', "do>*__think_'s__think_*"]

2521_3.q Do you think she's the fastest mover on the tour? How quick is she?
["do>*__think_'s__think_*", 'how>*__is_*']

5400_11.q You say sometimes in your matches you're a little bit up and down. Why do you think that is? Do you think there's something you can do to work on that to avoid the peaks in the matches?
['think_*__think_is__think_why', "do>*__think_'s__think_*"]

4367_2.q Is that one of the matches that you say, This is why it's exciting to play tennis, when you're playing that quality, it's so close, or do you just like to get out of there?
["'s_* is>* like_*__like_do"]

1991_11.q Is Vera like the Russians in any way? Is she unique? Does she remind you of any of the other Russian girls?
['is>*__is_*__is_in is>*__is_*__is_like', 'is>*', 'does>*']

6070_8.q Sometimes it seems if your game doesn't work you don't want to like just keep the ball in play; is that right? Is it too boring for you? You like playing longer rallies, higher over the net, or is it completely crazy the question I put?
['', 'is>*', 'is_* like_*']

5671_13.q Is it annoying or you like it?
['is>* like_*']

4032_1.q Is it the matchup that you like? You like the target at the net, that kind of thing?
['is>*', 'like_*']

3686_28.q The Australian tradition obviously is a great story. I'd like you to talk about in terms of respect, the code of conduct, is that important in today's game, or is it more of just a matter of winning at whatever costs, getting the Ws and prevailing?
['is_*__is_important is_*__is_like']

top responses:
5050_10.a If that's one of the options. You know, I don't think it's really necessary. I think what's necessary is that we consider all different sides of that rule that was implemented this year on the tour. I understand that they want to be more strict on the rule. That's why they came up with that. I respect that. No problem. I'm probably one of the few players that they are looking carefully and see how much time I spend on the court. I know that I maybe take more time than some other players. But as much as you know it's fair and you have this prewarning, I have no problem with it.
["'s_* 's_if if>*", "think_'s think_* think_do think_know", 'think_* think_is', 'understand_* understand_want', "'s_* 's_came", 'respect_*', '', "'m_* 'm_looking 'm_probably", 'know_* know_take', "but>* but>as have_'s have_*"]

5608_13.a This is a big test for me. I don't need Murray to have a further test. The draw is a very testing draw. I know it's tough. It's not easy for anybody right now at this stage of the tournament, because you don't want to have any hiccups right now. I hope I can continue playing at a high level. What I've shown over the last three to four months to myself is that I'm more confident, that I know I'm most likely going to play okay in my next match, which wasn't always the case midway through last year when I didn't know how I was going to feel actually during the match. I feel like I can think ahead. I can think tactics. I can think many things out there. Everything else but my body, and that's very positive. I've overcome a lot in the last few months.
['is_*', 'need_* need_do need_have', 'is_*', "know_'s know_*", "'s_* 's_at 's_easy 's_for 's_not 's_now 's_want", 'hope_* hope_continue', "is_'m is_* is_shown what>*", 'know_* know_going know_that that>*', 'feel_* feel_think', 'think_* think_can', 'think_* think_can think_there', '', "overcome_'ve overcome_* overcome_in"]

5659_10.a Uhm, not necessarily, you know. What's interesting about the bigger guys these days is that they play from the baseline. Whenever you were over 185, you used to serve and volley back in the day because you would take advantage of your size, of your power. And now it's all these guys over 190 are actually playing further back in the court because they have more time, their serve is as big as it is, and they don't need to kill themselves always running back and forth over hours and hours. That I think is something that has really changed. And, of course, when you're tall like this, the serving, it helps the serving. But, you know, I don't think it's impossible for a smaller guy to succeed in today's game. I mean, Rafa, me, we're not the tallest out there. We're the norm, let's say. And that works perfectly well. But, of course it is good to I guess be over 180. It just seems like it. But nevertheless I still believe you can do very well at 175, 180 as well.
['know_* know_uhm uhm>*', "is_'s is_* is_play what>*", 'used_* used_serve used_take used_were whenever>*', "and>* and>now is_'s is_* is_big need_* need_do need_kill", 'think_* think_is', "and>* helps_'re helps_* helps_of", "but>* think_'s think_* think_do think_know", "'re_* 're_mean 're_not 're_there", "let_'re let_* let_say", 'and>* works_* works_well', 'but>* is_* is_good is_of', 'be_* be_guess', 'seems_* seems_just seems_like', 'believe_* believe_do believe_nevertheless believe_still but>* but>nevertheless']

3171_6.a I always wish for Serena to play all the events because I think she's great for women's tennis. She's a great player, she's a great athlete. We all respect her a lot. But I think there is a very tough draw. Women's side is very strong at the moment. There are so many players that can go very far in the tournaments, and you can never predict it. I think this kind of challenge makes women's tennis very interesting. You know, even if Serena is not here, I really think there are so many great players out there. It is still a great competition.
['wish_* wish_always wish_play wish_think', "'s_'s 's_*", 'respect_*', 'but>* think_* think_is', 'is_* is_at is_strong', 'are_* are_there predict_* predict_can predict_never there>*', 'think_* think_makes', 'think_* think_are think_is think_know think_really', 'is_* is_still']

4972_5.a I always say the same. I don't like to be arrogant. I don't like to talk about a part of the history of tennis where I am involved because going to sound very arrogant if I say this era is great. A lot of eras are good. We had a lot of fantastic years in tennis. I think this era is special because the best players of the world, they have the ability to be in the final rounds of most of the tournaments. That's create a classic matches, good battles. But at the end there is very qualified people from the press, from past players, can analyze much better this era than me that I'm inside, that I'm involved in.
['say_* say_always', 'like_* like_be like_do', 'like_* like_do like_talk', 'are_* are_good', 'had_* had_in', 'think_* think_is', "create_'s create_*", "analyze_'m analyze_* analyze_better analyze_can but>* but>at is_* is_at is_from is_there"]

3616_18.a You can't think like that. You have to have your own mindset. If you think you have a chance because someone's not playing, that's a weak mentality to have. I'm a competitor. I like playing against the best. I love playing against champions. It's what makes it fun. I mean, it's what the game is all about.
['think_* think_ca think_like', 'have_* have_have', "'s_* 's_think if>*", "'m_*", 'like_* like_playing', 'love_* love_playing', "'s_* 's_makes", "'s_* 's_is 's_mean"]

5122_9.a I know je t'aime. That's important. No, I haven't improved my French speaking. I'm a little bit shy, because sometimes even though I live in Monaco, is difficult to speak. I understand a lot of French speaking, but it's hard because every time I try, French people can be a little bit tough on you if they don't understand. They say, Eh, eh? I'm shy and I start to speak English. But actually, I would love to improve that. I just don't have much time to learn.
['know_*', "'s_* 's_important", 'improved_* improved_have improved_no no>*', "'m_* 'm_shy is_* is_difficult is_live", "'s_* 's_be 's_hard understand_*", 'say_* say_eh', "'m_* 'm_shy", 'and>* start_* start_speak', 'but>* but>actually love_* love_actually love_improve love_would', 'have_* have_do have_just']

197_6.a I mean, it's true that it's like a big relief because we were all fighting there. To have already my place there, it's good. But I know also that Beijing is a mandatory tournament. It's really important for us. I'm just really motivated, like I said before, to try to finish good. It's great to be qualified. But tomorrow I have another match. It's like, What? I'm motivated for tomorrow, to keep this line.
["'s_'s 's_* 's_mean 's_true", "'s_* 's_good 's_have to>*", 'but>* know_* know_also know_is', "'s_* 's_for 's_important", "'m_* 'm_motivated 'm_said", "'s_* 's_be 's_great", 'but>* have_*', "'s_* 's_like 's_what", "'m_* 'm_keep 'm_motivated"]

4926_3.a I think rules are rules. They're put out there, so there is not much else I can say about it. I'm sure to put him off a little or something.
['think_* think_are', "is_* is_else is_not is_so is_there put_'re put_* put_out put_there", "'m_* 'm_sure"]

22_5.a Not really, because for me it doesn't really mean anything. It means, but it's not the main thing why I'm playing, to be 11 or in top 10. So there are few more spots to go and few more points. I hope if I can continue to play like this I will get there.
['mean_* mean_because mean_does mean_for mean_really not>*', "'s_* 's_be 's_not means_*", 'are_* are_so are_there so>* so>there', 'hope_* hope_get']

2974_10.a Usually when the rally is longer, that means that from the beginning you're doing something wrong. Especially me, because I'm a pretty aggressive player. I like to take the first ball and be in control of the point and not stand 20 feet back behind the baseline and play defense. That's not really my game. So if I'm in a long rally, it's not really about panicking, but about trying to get out that point and doing the best you can about winning it and going into the next one and being a little bit smarter.
['means_* means_doing means_is means_usually usually>* usually>when', '', 'like_* like_take', "'s_* 's_not 's_really", "'s_'m 's_* 's_about 's_not 's_really 's_so about_* about_trying so>* so>if"]

6362_20.a I don't know. I think it's always kind of been like that, so I always have to be ready. If I'm not, then I'm not. But I have to be ready for that. Since I do know that, it's no excuse. If they want to play well, that's great. It gives me great competition. I think it makes for a wonderful match. I have to be ready. I have to be ready to play anyone at any given time.
['know_* know_do', 'have_* have_always have_be have_so have_think', "'m_'m 'm_* 'm_not 'm_then if>*", 'but>* have_* have_be', "'s_* 's_know since>*", "'s_* 's_great 's_want if>*", 'gives_*', 'think_* think_makes', 'have_* have_be', 'have_* have_be']

3896_5.a I don't know. I think it's preference. I love being on a team. I mean, I love the Davis Cup aspect of it. But, you know, there's nothing like answering for yourself out there. There's sort of a sense of pride that I know tennis players have, and I'm sure golfers have, that it's just us out there. We don't have to rely on anyone. We don't need to rely on anyone. So I think there's a little sense of pride there.
['know_* know_do', "think_'s think_*", 'love_* love_being', 'love_* love_mean', "'s_* 's_know 's_there but>*", "'m_'s 'm_* 'm_sure 's_* 's_know 's_of 's_there there>*", 'have_* have_do have_rely', 'need_* need_do need_rely', "so>* think_'s think_* think_so"]

2650_8.a Not more than any other Grand Slam. You know, I think all the players are focusing on the Grand Slams. Everybody wants to win in the bigger tournaments. Paris is one of the biggest ones, so of course my main goal is to do well in the big tournaments. But there's still a lot of tennis to be played before Paris.
['more_* more_not more_than not>*', 'think_* think_focusing think_know', 'wants_* wants_win', 'is_* is_do is_of is_so', "'s_* 's_still 's_there but>* but>there"]

6048_13.a Well, I don't like these types of things, but I'd say I've won this one, this trophy, thanks to the whole team. My family, my kin, and all the fans, as well, those who are for me, support me, those who gave me their support and their affection. This is when I can feel more energy really, when I need this extra bit of energy. It's thanks to them. When it's tough during the match there are so many people around you who will help you. It's all the emotional support which I receive which makes me want to practice every day and make more effort every day. That's why I'm here today with you. Well, it's easy to say, but it's harder to do. You need to work hard throughout your tennis career. Well, the effort that you have to put in is huge.
["like_* like_do like_well say_'d say_* say_won well>*", 'support_*', 'is_* is_feel is_need', "'s_*", "are_'s are_* are_there when>*", "'s_*", "'s_'m 's_*", "'s_* 's_easy 's_harder 's_say 's_well well>*", 'need_* need_work', 'is_* is_huge is_well well>*']